name: Update badges

on:
  workflow_dispatch: # run manually
  schedule:
    # Runs at 1am UTC on Sunday
    - cron: "0 1 * * 0"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Badges - Readme
        uses: pemtajo/badge-readme@3.2
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true